### ISSUE TITLE
Errors in the example serverless.yml

### ISSUE THREAD

**Issue by adjohn** [iopipe/serverless-plugin-iopipe#31]
Plugin name `serverless-plugin-iopipe/index.js` is invalid
`IOPIPE_TOKEN` does not match the readme which is `iopipeToken`

**Comment by pselle** [comment]
`example` is what is run from within this folder, using the copy of the plugin as it is built in the repo, hence those paths and env var. We should update the naming/clarify.

**Comment by coreylight** [comment]
A true example was added here:
https://github.com/iopipe/serverless-plugin-iopipe/tree/master/example
And the test project was moved to `testProject`
