### ISSUE TITLE
Make `iopipeToken` optional if environment variable set

### ISSUE THREAD

**Issue by kolanos** [iopipe/serverless-plugin-iopipe#42]
If `IOPIPE_TOKEN` is set as an environment variable in the serverless.yml, then the `iopipeToken` custom var should be optional.

**Comment by coreylight** [comment]
I don't believe serverless plugins have access to env vars (for good reason) so we unfortunately cannot do this. We could, however add a `||` statement inside of the js code to fallback (again) to the env var.
