### ISSUE TITLE
Handler path separator incorrect on windows 

### ISSUE THREAD

**Issue by justin-gerhardt** [iopipe/serverless-plugin-iopipe#75]
The Lambda handler path is set using path.join which uses the native system path separator.  Using the windows path separator causes lambda to fail to import the handler.

**Comment by pselle** [comment]
@justin-gerhardt Thank you for the report! Can you please describe some replication steps? Are you running `sls invoke local` or are you seeing this issue when you deploy to Lambda?

**Comment by justin-gerhardt** [comment]
The issue occurs whenever attempting to deploy to lambda from windows. It should be fixable by changing line 403 of index.js to use path.posix.join rather than path.join.
