### ISSUE TITLE
Plugin does not work with individual function deploys 

### ISSUE THREAD

**Issue by khrome83** [iopipe/serverless-plugin-iopipe#84]
**Description**

**Steps to reproduce the issue:**
1. Install IO|, serverless-plugin-iopipe, and other depdencies correctly
2. Create simple hello world function
2. Run `sls deploy`
3. Execute function and notice works as expected, including reporting to IO|
3. Run `sls deploy function -f myFuncName`
4. Execute function and notice error in response and no reporting to IO|

**Describe the results you received:**

##### 502 Bad Gateway

``` json
{
    "message": "Internal server error"
}
```

IO Pipe will not show error or record the execution.

##### AWS Cloudwatch Logs

```css
Unable to import module 'iopipe_handlers/diffScreenshots-0-iopipe': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
```

**Describe the results you expected:**

When deploying a individual function, I expect the IO Pipe plugin to work the same as deploying the entire stack.

**Application and library versions**

```json
{
"devDependencies": {
    "serverless": "1.27.3",
    "serverless-apigw-binary": "0.4.4",
    "serverless-apigwy-binary": "0.1.0",
    "serverless-domain-manager": "2.4.0",
    "serverless-dynamodb-local": "0.2.30",
    "serverless-offline": "^3.20.3",
    "serverless-plugin-iopipe": "1.5.2",
  },
  "dependencies": {
    "@iopipe/iopipe": "1.8.0",
  }
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This only occurs when running `sls deploy function -f myFuncName`

**Comment by coreylight** [comment]
Fixed with https://github.com/iopipe/serverless-plugin-iopipe/pull/89
