### ISSUE TITLE
SLS invoke local not working with Serverless Framework versions > 1.32.0

### ISSUE THREAD

**Issue by adjohn** [iopipe/serverless-plugin-iopipe#94]
There seems to be a regression with the latest versions of the serverless framework when using `sls invoke local` and IOpipe.  There are no errors, but the telemetry is not sent to IOpipe when running invoke local.   

The workaround is to downgrade serverless framework to version 1.32.0

**Comment by ewindisch** [comment]
@mrickard this is affecting at least one user contacting support! Thanks!

**Comment by ewindisch** [comment]
@mrickard was this resolved with the commit to unpin the sls framework version?

**Comment by mrickard** [comment]
@ewindisch I think so: the two likely culprits were 
1) a regression in recent versions of the module (as identified by @adjohn)
2) a default assignment of "id" to the awsRequestId for locally invoked events (as identified by @kolanos)

I pinned the version and assigned a UUID to the request IDs for locally invoked functions, so these two potential causes for non-logging functions were addressed in the merge.

**Comment by ewindisch** [comment]
Great if/as this is confirmed we should close the issue! Thanks. I'll communicate to the user I was speaking with and have them upgrade.

**Comment by mrickard** [comment]
Excellent.  In my tests I'm getting both local and AWS invocations in a dashboard.
